# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.4]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: supercharge/mongodb-github-action@1.3.0
        name: Start MongoDB
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm ci
      - run: npm test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Build docker stack
      - uses: jakejarvis/wait-action@master
        name: Check running containers
        with:
          time: '60s'
      
      - run: docker-compose up -d
      - run: docker ps -a

